#!/bin/sh

alias vi="nvim"

alias ls="exa --color=always --group-directories-first"
alias ll="exa -l --color=always --group-directories-first"
alias la="exa -la --color=always --group-directories-first"

alias cp="cp -v"

alias grep="grep --color=auto"


# Fuzzy find configuration files
cf() {
	files=$(find "$HOME/Projects/dotfiles" \
                 "$HOME/.config/dwm" \
                 "$HOME/.config/dwmblocks" \
                 "$HOME/.config/dmenu" \
                 "$HOME/.config/nvim" \
                  -not -path "*/\.git*")

	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || open "$selected"
}

# Fuzzy find university directory
uni() {
	files=$(find "$HOME/Universidade" -not -path "*/\.git*")
	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || open "$selected"
}

# Fuzzy find projects directory
proj() {
	files=$(find "$HOME/Projects" -not -path "*/\.git*")
	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || open "$selected"
}
