#!/bin/sh

alias vi="nvim"

alias ls="exa --color=always --group-directories-first"
alias ll="exa -l --color=always --group-directories-first"
alias la="exa -la --color=always --group-directories-first"

alias cp="cp -v"

alias grep="grep --color=auto"


# Fuzzy find configuration files
cf() {
	files=$(find "$HOME/repos/dotfiles" \
	             "$HOME/.config/dmenu" \
	             "$HOME/.config/dwm" \
	             "$HOME/.config/nvim" \
	             -not -path "*/\.git*" |
	             sed "s/repos\/dotfiles\/[a-z]*\///" |
	             sort -u)

	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || xdg-open "$selected"
}

# Fuzzy find university directory
uni() {
	files=$(find "$HOME/uni" -not -path "*/\.git*" | sort)
	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || xdg-open "$selected"
}

# Fuzzy find repositories directory
rep() {
	files=$(find "$HOME/repos" -not -path "*/\.git*" | sort)
	selected=$(echo "$files" | fzf)
	[ "$selected" = "" ] && return
	[ -d "$selected" ] && cd "$selected" || xdg-open "$selected"
}
