#!/bin/sh

alias vi="nvim"

alias ls="exa --color=always --group-directories-first"
alias ll="exa -l --color=always --group-directories-first"
alias la="exa -la --color=always --group-directories-first"

alias cp="cp -v"

alias grep="grep --color=auto"


# Main way of editing configuration files
ed() {
	# Dotfiles repository path
	repo_dir="$HOME/Projects/dotfiles"

	# List of all files to link
	files=$(find "$repo_dir" -type f | grep -v -e ".git" -e "md" -e "setup" | sed "s|${repo_dir}|${HOME}|")
	echo "$files" | fzf | xargs -r $EDITOR
}

uni() {
    open $(du -a --exclude=.git $HOME/Universidade | awk "{print $2}" | fzf)
}

proj() {
    open $(du -a --max-depth=1 $HOME/Projects | awk "{print $2}" | fzf)
}
