#!/usr/bin/sh

alias vi="nvim"

alias ls='exa --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias la='exa -al --color=always --group-directories-first' # my preferred listing

alias weather='curl wttr.in/Lisbon'

cfg() {
    open $(du -a --exclude .git \
                 --exclude $HOME/.config/nvim/plugged \
              $HOME/.xinitrc \
              $HOME/.Xresources \
              $HOME/.zprofile \
              $HOME/.config/zsh/.zshrc \
              $HOME/.config/alias \
              $HOME/.config/zoomus.conf \
              $HOME/.config/alacritty \
              $HOME/.config/nvim \
              | awk '{print $2}' | fzf )
}

sc() {
    du -a $HOME/.local/bin/scripts/* $HOME/.local/bin/statusbar/* | awk '{print $2}' | fzf | xargs -r $EDITOR
}

uni() {
    open $(du -a $HOME/Universidade | awk '{print $2}' | fzf)
}

proj() {
    open $(du -a --max-depth=1 $HOME/Projects | awk '{print $2}' | fzf)
}
